dist: trusty
sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  slack:
    secure: fZm+zCC391+EzUc2FprOO/MVtvfXjhizt0EXNX4aRWwZnPkkmpiqfdZ1XCx5BslsDw5ExvTT5UGyDCXqMbigJ+dVVEdGb5ENW/NG+6o7/0//fKWx47xMIkgnbxKR6oKHhS45g8hu6KpyTUXhkR5ANmWW2SteRE1O8/QQwvOE+V6YkQd4MEK1VHPJhnwybOBDKAZqgfxNRitOwa0xXxM1hRKK5mt1grAtdh+F4y/0GdjDVORugfk/115cnlRjONEHrk1f5QMLxXBF/Q/Nl2UPSqeYUUsJPwooEFU68qN0r0Ddwua+BCeYMVgKsgqAGbCj0ySj86akG0ihyKLLSk0sLbMn5PmdI+5OQcMu+JZUebYiK/+uxzem1NrU6VVRi8jiErKWnNv3qwPvB+NUX2Ny3gfg7cn4AQfqKdqvJzJRjB0kY6keHLLr8+oAsTOD2wGB2hPG+oy8lg9LpkFJIvcZfOmJKaa+yNSJHIEm5cjpWreFOhOms69U2cwjpDEmC0EfkILmmPmFfyhlws+BWSObsZLFkgAjJt2QvMnBPht2H+BPDLQW1VfzF+bRuL3F0ItIXVOFjMtum5Oz8GPWUJqK8FymyQAqlfXGmUI/XYeFR5qc9/QBWvKAoSXBwVxS6LbwWkptN3tg0I9DiztjHpGtgtT+IPiDXpfKq+nZRUeRFWo=
script:
  - NODE_ENV=production npm run build
deploy:
  provider: s3
  region: us-west-1
  bucket: pf9-ui
  access_key_id: AKIAJHCL5SIVALO2BVPQ
  secret_access_key:
    secure: Jz8fH7INKrFlZ6tCcdzEMYzMDqSXPEeFJf5wy+NoeVDF/jMpFmWkU7oZ5t3dOIKqNqKMRuy2KyBGUJU7CLwdr9m/zQyARKKkVsegFbSiIuuMZQIvhDzx3DF+jrYE+iIEbTy4bN/1rtgQlo+AIExBvwI1J+E4hyQg8uYotGoVqkHYjSFwWSfxVu1HOODz2Oh2CZPuxKQRh+WMyIXKh+PRdpcNURnEwmSSeFoA2YRx5cX5iphhSxo3A5uyWWSxOkPE9EqH0Ccnz/ZBflqsvnb05BObJt8CfOSE1UvrQa8jwNL189MqvTRv9GyRNvFxcnXUklQvBLh5wDyy5g7QK8RDkaK9vnaxWWu3g+xYqvzVFIrni2HmZrIM2QWI7qrSi2l5q2tehNoQM9016C/fs+IeaWl9kzWyc1+aG+vT2sV0ymtppwxVohpojmC4WoVZpbaYXIAU2dUlzRekuKULJeT6n4mURBOALnjcmMH+hv1RlhVX+zNGmov/uAn4KRey8VMQpV6foCYR+jlo5pzMSrTOh3OgMdUlaj3rehCoqECtzOYWJEEoxkWw3Lz5CjwECnT8d9W19e+cLD1YVIVzvLV7pc4v4WCn47LOObkVY6SBhyW7UersB7EqERPZhOQF3+yMyMSKawAOAqxPzYHagSGOmpLISmIKR8XJRbWTLtPKz9k=
  acl: public_read
  local_dir: build
  upload-dir: master
  skip_cleanup: true
